### ISSUE TITLE
Include a package for Julia users

### ISSUE THREAD

**Issue by JinraeKim** [fdcl-data-driven-control/data-driven-control#1]
이 레포에서 줄리아 패키지를 담을 수 있도록 하려면 어떻게 해야할까요?
@hnlee77

**Comment by minii93** [comment]
결국 이렇게.. Julia의 늪으로..🤣

**Comment by JinraeKim** [comment]
레포 하나를 더 파서 (예: DataDrivenControl.jl) 서브모듈로 넣어야하나?

**Comment by JinraeKim** [comment]
> 결국 이렇게.. Julia의 늪으로..🤣

안 쓰고 싶음 안 써도 될듯 ㅎㅎ
새로 배우는 나쁘지 않은 기회일수도 있고... ㅋㅋㅋㅋ

**Comment by minii93** [comment]
> > 결국 이렇게.. Julia의 늪으로..🤣
> 
> 안 쓰고 싶음 안 써도 될듯 ㅎㅎ 새로 배우는 나쁘지 않은 기회일수도 있고... ㅋㅋㅋㅋ

새로 배우는 나쁘지 않은 기회라는 데 한표ㅋㅋㅋㅋㅋㅋ

**Comment by hnlee77** [comment]
> 레포 하나를 더 파서 (예: DataDrivenControl.jl) 서브모듈로 넣어야하나?

이런게 가능하다면 좋을 것 같네요? 혹은 지금 이 방법 말고 organization을 하나 파서 거기에 필요한 언어별로 레포를 파는 방식은 어때요?

**Comment by hnlee77** [comment]
> > > 결국 이렇게.. Julia의 늪으로..🤣
> > 
> > 
> > 안 쓰고 싶음 안 써도 될듯 ㅎㅎ 새로 배우는 나쁘지 않은 기회일수도 있고... ㅋㅋㅋㅋ
> 
> 새로 배우는 나쁘지 않은 기회라는 데 한표ㅋㅋㅋㅋㅋㅋ

이게 가능하다면 이걸 줄리아 레포로..ㅎ

**Comment by minii93** [comment]
> > > > 결국 이렇게.. Julia의 늪으로..🤣
> > > 
> > > 
> > > 안 쓰고 싶음 안 써도 될듯 ㅎㅎ 새로 배우는 나쁘지 않은 기회일수도 있고... ㅋㅋㅋㅋ
> > 
> > 
> > 새로 배우는 나쁘지 않은 기회라는 데 한표ㅋㅋㅋㅋㅋㅋ
> 
> 이게 가능하다면 이걸 줄리아 레포로..ㅎ

안돼.. 100% 줄리아는 리젝합니다

**Comment by hnlee77** [comment]
organization 방식은 어떻씁네까?

**Comment by JinraeKim** [comment]
> organization 방식은 어떻씁네까?

나쁘진 않습니다 (안 해봐서 side effect 예측이 안되네).

**Comment by JinraeKim** [comment]
submodule? 이런거 혹시 써보심?

하나의 깃헙 레포에서 하위 레포 동시 개발 가능?
@minii93

**Comment by JinraeKim** [comment]
대충 찾아보니 가능한 것 같네요.
@hnlee77 서브모듈로 만들면 될듯?

**Comment by JinraeKim** [comment]
> 대충 찾아보니 가능한 것 같네요. @hnlee77 서브모듈로 만들면 될듯?

**Comment by JinraeKim** [comment]
그럼 이 친구의 소유자를 [organisation](https://github.com/fdcl-data-driven-control) 으로 옮기면 될듯

**Comment by minii93** [comment]
> submodule? 이런거 혹시 써보심?
> 
> 하나의 깃헙 레포에서 하위 레포 동시 개발 가능?
> @minii93 

넹 서브모듈 쓰면 두 개의 레포 모두 개발 가능!

**Comment by hnlee77** [comment]
소유자를 옮겼습니다. 이 organization 내에서 서브모듈 등을 추가로 넣으면 되겠습니다!

**Comment by JinraeKim** [comment]
@hnlee77  근데 기존의 [ApproximateDPs.jl](https://github.com/hnlee77/ApproximateDPs.jl) 를 옮겨올 것인가요, 아니면 처음부터 다시 할까요? (ADP에 국한되지 않는건가?)

**Comment by hnlee77** [comment]
> @hnlee77 근데 기존의 [ApproximateDPs.jl](https://github.com/hnlee77/ApproximateDPs.jl) 를 옮겨올 것인가요, 아니면 처음부터 다시 할까요? (ADP에 국한되지 않는건가?)

ADP에 국한되지 않도록 하기로 했던 것 같지만 필요하다면 여기에 옮겨와도 좋을 것 같긴 하네요~

**Comment by JinraeKim** [comment]
@hnlee77 그럼 일단 여기에 서브모듈로 새로 만들고, 필요성이 느껴지면 일부 기능을 옮겨오던가 해도 되겠군여

**Comment by hnlee77** [comment]
> @hnlee77 그럼 일단 여기에 서브모듈로 새로 만들고, 필요성이 느껴지면 일부 기능을 옮겨오던가 해도 되겠군여

고런 방법도 있겠군요! 그렇게 합시다 ㅎㅎ

**Comment by JinraeKim** [comment]
@hnlee77 [DataDrivenControl.jl](https://github.com/fdcl-data-driven-control/DataDrivenControl.jl) 을 만듦
