### ISSUE TITLE
Review concurrent learning

### ISSUE THREAD

**Issue by minii93** [fdcl-data-driven-control/data-driven-control#2]
논문 리뷰를 하다가 마주친 김에 간단하게 공부를 할 생각이니, 혹시 함께할 사람이 있다면 얘기해주세요!

**Comment by hnlee77** [comment]
다른 관련 논문을 찾아보려는 건가요?

**Comment by minii93** [comment]
> 다른 관련 논문을 찾아보려는 건가요?

그렇지요?! 그냥 개념 정도만 알 수 있으면 좋을 것 같은데, 어떤 논문이나 책을 볼지는 찾아봐야할듯?!ㅋㅋㅋ

**Comment by JinraeKim** [comment]
[이게](https://ieeexplore.ieee.org/document/5717148/) 시초로 알고 있고, [비행제어 (link updated)](https://arc.aiaa.org/doi/abs/10.2514/1.46866) 에도 적용된거로 앎

**Comment by minii93** [comment]
시초 논문이 나름 최근 논문이군?! 좋넹

**Comment by hnlee77** [comment]
> [이게](https://ieeexplore.ieee.org/document/5717148/) 시초로 알고 있고, [비행제어 (link updated)](https://arc.aiaa.org/doi/abs/10.2514/1.46866) 에도 적용된거로 앎

저도 함께 읽어보겠습니다.

**Comment by minii93** [comment]
> > [이게](https://ieeexplore.ieee.org/document/5717148/) 시초로 알고 있고, [비행제어 (link updated)](https://arc.aiaa.org/doi/abs/10.2514/1.46866) 에도 적용된거로 앎
> 
> 저도 함께 읽어보겠습니다.

그렇다믄 1주일 정도 시간을 두고 읽어보면서 막히는 부분이 있으면 서로 얘기해보기로 할까?!

**Comment by JinraeKim** [comment]
저는 논문은 한번 본 적이 있어서, 다시 읽지는 않고 깃헙의 토론을 구경하는 정도로 하겠습니다 ㅎㅎ

**Comment by Youngjun-Lee-FDCL** [comment]
> [이게](https://ieeexplore.ieee.org/document/5717148/) 시초로 알고 있고, [비행제어 (link updated)](https://arc.aiaa.org/doi/abs/10.2514/1.46866) 에도 적용된거로 앎

 저도 join

**Comment by minii93** [comment]
오늘이 목요일이니까 **다음 주 목요일** 정도까지 시초 논문을 읽어보는 것이 어때요?
(사실 저는 이미 읽는 중)

**Comment by minii93** [comment]
논문을 읽다가 쪼금 멈칫했던 부분들을 정리해보았으니 읽을 때 잘 안 읽히면 참고해도 좋을 것 같아요!!

![2021-12-31  Concurrent Learning_1](https://user-images.githubusercontent.com/96710072/147797787-7cd7121e-e333-4cb9-a874-411ecd81920b.jpg)
![2021-12-31  Concurrent Learning_2](https://user-images.githubusercontent.com/96710072/147797788-4925ddb5-5d76-48c6-b852-049f8f58060b.jpg)

**Comment by JinraeKim** [comment]
@minii93 [위 필기](https://github.com/fdcl-data-driven-control/data-driven-control/issues/2#issuecomment-1003234596)의 첫 페이지 중 아래 부분은 thm 2 -> thm 3 가 되야할듯~

대충 요약하자면, 과거의 데이터를 (rank 조건을 만족하도록 충분히, 또는 잘) 모으면 "instantaneous data" 만 쓰는 적응 제어에 비해 조건이 완화될 수 있다는 것 같군요 (PE 조건 등).

주요 내용은
Thm 1: concurrent learning
Thm 2: concurrent learning for adaptive control
Thm 3: concurrent learning for adaptive control with projection

인 것 같네요.

질문: projection 이 있어서 좋은 점을 잘 이해하지 못했는데, Thms 2, 3 의 차이가 무엇일까요?

**Comment by minii93** [comment]
> @minii93 [위 필기](https://github.com/fdcl-data-driven-control/data-driven-control/issues/2#issuecomment-1003234596)의 첫 페이지 중 아래 부분은 thm 2 -> thm 3 가 되야할듯~
> 
> 대충 요약하자면, 과거의 데이터를 (rank 조건을 만족하도록 충분히, 또는 잘) 모으면 "instantaneous data" 만 쓰는 적응 제어에 비해 조건이 완화될 수 있다는 것 같군요 (PE 조건 등).
> 
> 주요 내용은 Thm 1: concurrent learning Thm 2: concurrent learning for adaptive control Thm 3: concurrent learning for adaptive control with projection
> 
> 인 것 같네요.
> 
> 질문: projection 이 있어서 좋은 점을 잘 이해하지 못했는데, Thms 2, 3 의 차이가 무엇일까요?

그러네요ㅎㅎ

사실 projection을 도입한 동기 자체는 현 시점의 정보로 적응하기 어려울 때만 과거의 데이터를 이용하여 적응하겠다는 개념인 것 같은데.. projection이 있어서 성능이 더 좋아지는 것 같지는 않고 실제로 시뮬레이션 결과에서도 정리 2의 방식이 가장 좋은 성능을 보인다고 얘기하고 있어요. (projection이 있으면 좋은지 아직 고민이 더 필요한듯?)

**Comment by JinraeKim** [comment]
내가 바보라 이해 못한 게 아니었군... 다행이다 (?) ㅋㅋㅋ

**Comment by seong-hun** [comment]
CL 관련해서는 부끄럽지만 제가 submit한 논문의 intro를 읽어보는 것도 도움이 될 듯 합니다 (필요한 사람은 메일로 줄게요)

**Comment by JinraeKim** [comment]
@seong-hun 인트로만 캡처로 공유해주시거나 preprint 올리는건 조금 무리수?
(무리수면 메일로 부탁드립니다요 ㅎㅎ)

**Comment by seong-hun** [comment]
받으실 메일 여기 알려주시면 거기로 보내드릴게요~

**Comment by JinraeKim** [comment]
> 받으실 메일 여기 알려주시면 거기로 보내드릴게요~

kjl950403@gmail.com

**Comment by JinraeKim** [comment]
@seong-hun 질문 남깁니다:
식 (3) 의 `\xi`, `y` 가 각각 어떤 값인지 잘 이해를 하지 못했는데, 설명 부탁드립니다.
(뭔가 측정된 값? 인가요? 혹시 그렇다면, 무엇을 측정한 값일까요?)

![image](https://user-images.githubusercontent.com/43136096/148153345-d9d655be-1b3a-4f64-b95f-de30f8c7c2c8.png)


그리고 식 (1b) 의 `x^T PB` 부분은 `e^T PB` 가 되야하지 않을까 생각됩니다~

![image](https://user-images.githubusercontent.com/43136096/148153994-c8f2bbd3-7bce-4ce1-b9fa-0085e3632ccf.png)

* 캡처된 부분은 원하시면 삭제하겠습니다

**Comment by seong-hun** [comment]
앗 이것은 수정 전 버전이구만.. ㅎㅎ 인트로만 읽으랬더니 어디까지 읽고 있는 것인가요...?ㅋㅋㅋ

> 식 (3) 의 \xi, y 가 각각 어떤 값인지 잘 이해를 하지 못했는데, 설명 부탁드립니다.

W^\circ를 저런 방식으로 추정하는 기법들이 CL류의 기법들입니다. 해당 부분은 리뷰가 오면 수정하려고 했었는데 예리하시네요ㅎㅎ

> 그리고 식 (1b) 의 `x^T PB` 부분은 `e^T PB` 가 되야하지 않을까 생각됩니다~

맞습니다~

**Comment by seong-hun** [comment]
아 저게 인트로 내용이구나...

**Comment by JinraeKim** [comment]
ㅋㅋㅋㅋ 인트로만 보고 있는데 ㅎㅎ...

다시 읽어보니 `\xi` 는 `phi(x)` (regressor vector) 의 관측치, `y` 는 `\delta(t, x)` (불확실성) 의 관측치 정도 되려나요...?

어쨌든 정리된 form (1a), (1b) 로 보니까 이해가 더 잘 되네요 ㅋㅋㅋㅋ

**Comment by seong-hun** [comment]
넵 그렇게 보시면 됩니다 ㅎㅎ

**Comment by JinraeKim** [comment]
그럼 loss function `l` 은

`0.5 W^T F' W - G^T W`

형태로 잡는거고, 이것을 `W` 에 대해 미분해서 `0.5(F'+F'^T)*W - G` =: `F*W - G` (F in S^n_{++} is symmetric) 인데,
`W = F^{-1}G` for invertible `F` (minimum eigenvalue > 0) 인 것이군요.
`F^{-1}G` 는 계산해보면 (`\epsilon = 0` 일 때) `W^{\circ}` 가 나오고...

이제서야 공부를 시작해서 어려움을 겪고 있었는데, 덕분에 왜 많은 파라미터 추정 기법의 형태가 `\phi \phi^T` 와 `\phi y^T` 텀들을 가져가는지 이해가 되네요...! 감사합니다~


P.S. 아래에서  "equivalently, `F(t) ∈ Sn++`" 부분은 뭔가 "equivalently, `F(t) ∈ Sn++ is symmetric`" 이 되는게 좀 더 명쾌할 것 같습니다 (예: nonsymmetric matrix [1 1; -1 1] 또한 Sn++ 의 원소임을 고려하면)
![image](https://user-images.githubusercontent.com/43136096/148156149-b0e6774d-5836-424d-a9a5-8dcf0aa4f98a.png)

**Comment by JinraeKim** [comment]
@seong-hun 제가 얼핏 듣기로, "현재 데이터"만을 사용하는 일반적인 적응제어 세팅에서는 PE <=> exponential convergence 라고 들었는데, 혹시 관련 정리가 담긴 참고문헌이 있을까요? (증명이나, 참고문헌의 구체적인 정리 번호를 알려주시면 더 감사...!)

**Comment by seong-hun** [comment]
> @seong-hun 제가 얼핏 듣기로, "현재 데이터"만을 사용하는 일반적인 적응제어 세팅에서는 PE <=> exponential convergence 라고 들었는데, 혹시 관련 정리가 담긴 참고문헌이 있을까요? (증명이나, 참고문헌의 구체적인 정리 번호를 알려주시면 더 감사...!)

아래 정보로는 조금 부족한가요?

<img width="634" alt="image" src="https://user-images.githubusercontent.com/9782545/148157478-c16d6729-f541-4cc7-97ca-8e143c769932.png">

**Comment by seong-hun** [comment]
> P.S. 아래에서 "equivalently, `F(t) ∈ Sn++`" 부분은 뭔가 "equivalently, `F(t) ∈ Sn++ is symmetric`" 이 되는게 좀 더 명쾌할 것 같습니다 (예: nonsymmetric matrix [1 1; -1 1] 또한 Sn++ 의 원소임을 고려하면)

제안 감사합니다^^ 앞에 나온 정의 부분에서 그 내용을 써 놓는게 낫겠네요. 당연히 포함하면서 점점 더 작아지는 집합으로 이해할 것으로 생각했는데.. 분명히 할 수록 좋겠습니다.

<img width="613" alt="image" src="https://user-images.githubusercontent.com/9782545/148157592-a7af46aa-5663-48ab-9b28-1f79e9751f11.png">

**Comment by JinraeKim** [comment]
형이 공유해주신 심형보 교수님의 글(https://github.com/fdcl-data-driven-control/data-driven-control/issues/7#issuecomment-1005265664) 처럼 쓰면 본문 및 정의를 안 건드려도 되는 이점이 있을듯:

![image](https://user-images.githubusercontent.com/43136096/148157741-a9c2284c-d808-4039-aad8-c0240dd65046.png)

**Comment by seong-hun** [comment]
> 형이 공유해주신 심형보 교수님의 글([#7 (comment)](https://github.com/fdcl-data-driven-control/data-driven-control/issues/7#issuecomment-1005265664)) 처럼 쓰면 본문 및 정의를 안 건드려도 되는 이점이 있을듯:

이것도 좋지만, Technical Note의 분량 압박 때문에 다음과 같이 해보려고 합니다..ㅋㅋ
<img width="573" alt="image" src="https://user-images.githubusercontent.com/9782545/148158076-f70c91d3-7713-4540-b0b6-a17d0da24918.png">

**Comment by JinraeKim** [comment]
@seong-hun

제가 공저자도 아닌데 자꾸 말을 하게 되어 죄송합니다만 자꾸 보여서... ㅋㅋㅋㅋ

인트로에 (A, Q) is observable -> (A, \sqrt{Q}) is observable

**Comment by seong-hun** [comment]
> @seong-hun
> 
> 제가 공저자도 아닌데 자꾸 말을 하게 되어 죄송합니다만 자꾸 보여서... ㅋㅋㅋㅋ
> 
> 인트로에 (A, Q) is observable -> (A, \sqrt{Q}) is observable

어유 감사드리죠 ㅎㅎ 하지만 제가 알기론 (A, Q) is observable -> (A, \sqrt{Q}) is observable 이 성립합니다.

**Comment by minii93** [comment]
@hnlee77 @Youngjun-Lee-FDCL 혹시 논문을 읽고 있을까요?! 아직 안 읽었다면 읽고 나서 다음 주 월요일 1시에 간단하게 30분 정도 얘기하는 시간을 가지는 건 어때요?

**Comment by Youngjun-Lee-FDCL** [comment]
굳!

**Comment by hnlee77** [comment]
좋아욥

**Comment by minii93** [comment]
오늘 리뷰한 [내용](https://jelly-dirt-c4a.notion.site/CL-Review-639463e03dc643bcbeb9c57d92df7031) 이고,
다음 번에 리뷰할 [논문](https://ieeexplore.ieee.org/document/7810385/) 입니다.

리뷰에 대한 논의는 대략 1~2주 정도 후에 진행!

**Comment by JinraeKim** [comment]
> 오늘 리뷰한 [내용](https://jelly-dirt-c4a.notion.site/CL-Review-639463e03dc643bcbeb9c57d92df7031) 이고, 다음 번에 리뷰할 [논문](https://ieeexplore.ieee.org/document/7810385/) 입니다.
> 
> 리뷰에 대한 논의는 대략 1~2주 정도 후에 진행!

다음 리뷰는 다른 이슈로 파도 좋을 것 같음 ㅎㅎ

**Comment by minii93** [comment]
> > 오늘 리뷰한 [내용](https://jelly-dirt-c4a.notion.site/CL-Review-639463e03dc643bcbeb9c57d92df7031) 이고, 다음 번에 리뷰할 [논문](https://ieeexplore.ieee.org/document/7810385/) 입니다.
> > 리뷰에 대한 논의는 대략 1~2주 정도 후에 진행!
> 
> 다음 리뷰는 다른 이슈로 파도 좋을 것 같음 ㅎㅎ

아, 그쳐ㅋㅋ

**Comment by JinraeKim** [comment]
리뷰가 끝나서 이 이슈를 닫음; 추가 리뷰는 새로운 이슈로 진행 예정
