### ISSUE TITLE
(질문) 왜 많은 adaptive 방식의 ADP 는 actor-critic 구조를 가져가는가?

### ISSUE THREAD

**Issue by JinraeKim** [fdcl-data-driven-control/data-driven-control#22]
궁금증이 있는데요.

일반적인 LQ (in input) 형태의 최적제어 문제에서, 대체로 critic parameter 외에 actor parameter 를 두고 안정성을 보입니다.
여기 궁금한게, critic parameter 만 두고 (즉, actor parameter = critic parameter) 단순히 (HJB error estimate)^2 를 0으로 보내는 gradient update 로는 안정성을 보이기가 어려워서 actor parameter 와 같은 장치를 두는 것일까요? (그러면, 단순히 HJB error estimate 를 0으로 보내는 것이 실질적으로 critic parameter 가 최적 value function 의 parameter 로 수렴하기 어려움을 암시하는걸까요?)

제가 이쪽으로 공부가 부족해서 질문 드립니다 ㅎㅎ

**Comment by hnlee77** [comment]
> 궁금증이 있는데요.
> 
> 일반적인 LQ (in input) 형태의 최적제어 문제에서, 대체로 critic parameter 외에 actor parameter 를 두고 안정성을 보입니다. 여기 궁금한게, critic parameter 만 두고 (즉, actor parameter = critic parameter) 단순히 (HJB error estimate)^2 를 0으로 보내는 gradient update 로는 안정성을 보이기가 어려워서 actor parameter 와 같은 장치를 두는 것일까요? (그러면, 단순히 HJB error estimate 를 0으로 보내는 것이 실질적으로 critic parameter 가 최적 value function 의 parameter 로 수렴하기 어려움을 암시하는걸까요?)
> 
> 제가 이쪽으로 공부가 부족해서 질문 드립니다 ㅎㅎ

1. 아마도 actor 없이는 안정성분석에 어려움이 있을 것 같다는 예상
2. critic 만으로 설계된 알고리즘의 경우 batch update 형태를 주로 가져감

### 의문
- Policy iteration의 최적해로의 수렴성 증명이 있나 at 비선형 시스템?

**Comment by JinraeKim** [comment]
+)

> 1. 아마도 actor 없이는 안정성분석에 어려움이 있을 것 같다는 예상

그 어려움이 무엇인지 구체화할 수 있을지?

**Comment by JinraeKim** [comment]
대략, 안정성 분석에서의 어려움으로 인해 actor critic 구조를 가져가는 것으로 보이며, 추가 질문이 없는 것으로 판단하여 이 이슈를 닫음
