### ISSUE TITLE
Follow up the most basic ADP algorithm

### ISSUE THREAD

**Issue by JinraeKim** [fdcl-data-driven-control/data-driven-control#3]
For example, linear dynamics and quadratic running cost.

Gonna be useful to understand ADP algorithms and decide some code structures in this repo.

**Comment by JinraeKim** [comment]
Any suggestion? e.g. papers

**Comment by JinraeKim** [comment]
@hnlee77 joined

**Comment by hnlee77** [comment]
가장 기초적인 알고리즘으로는 다음 논문을 제안합니다.
[1] F. L. Lewis, D. Vrabie, and K. G. Vamvoudakis, “Reinforcement Learning and Feedback Control: Using Natural Decision Methods to Design Optimal Adaptive Controllers,” IEEE Control Syst., vol. 32, no. 6, pp. 76–105, Dec. 2012, doi: 10.1109/MCS.2012.2214134.

**Comment by JinraeKim** [comment]
ok

**Comment by JinraeKim** [comment]
[이 프로젝트](https://github.com/orgs/fdcl-data-driven-control/projects/1) 로 진행하겠습니다

**Comment by minii93** [comment]
주요 논문을 리뷰하는 것이군?!

**Comment by minii93** [comment]
> [이 프로젝트](https://github.com/orgs/fdcl-data-driven-control/projects/1) 로 진행하겠습니다

접근 권한이 없는 것 가타여

**Comment by JinraeKim** [comment]
@hnlee77 organisation 에 사람들을 초대해야할듯?

**Comment by hnlee77** [comment]
@minii93 @Youngjun-Lee-FDCL 이미 초대를 하였으나 ㅠㅠ 보류중이라고 한다..ㅎㅎ

**Comment by Youngjun-Lee-FDCL** [comment]
Sorry for late accept!

**Comment by minii93** [comment]
> @minii93 @Youngjun-Lee-FDCL 이미 초대를 하였으나 ㅠㅠ 보류중이라고 한다..ㅎㅎ

초대가 메일로.. 오는 것일까요? GitHub에서 온 것 같은 메일을 봤던 것 같은 것이 제가 실수로 지워버린 것 같은데
혹시 다시 초대.. 가 가능한 것일까..요?
미안합니다..ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by minii93** [comment]
다행히 Git에서 찾았어요..!!!

**Comment by hnlee77** [comment]
> 다행히 Git에서 찾았어요..!!!

ㅋㅋㅋㅋㅋㅋㅋ다행이에요ㅎㅎ

**Comment by JinraeKim** [comment]
> 가장 기초적인 알고리즘으로는 다음 논문을 제안합니다. [1] F. L. Lewis, D. Vrabie, and K. G. Vamvoudakis, “Reinforcement Learning and Feedback Control: Using Natural Decision Methods to Design Optimal Adaptive Controllers,” IEEE Control Syst., vol. 32, no. 6, pp. 76–105, Dec. 2012, doi: 10.1109/MCS.2012.2214134.

해당 논문은 https://github.com/fdcl-data-driven-control/DataDrivenControl.jl/issues/16 에서 다뤄졌고, https://github.com/fdcl-data-driven-control/DataDrivenControl.jl/pull/18 에 코드가 구현되었으므로 본 이슈를 닫음.

추가 논의가 필요하다고 생각하면 자유롭게 reopen 바람
