### ISSUE TITLE
Q) Kleinman 기법을 온라인으로 쓸 때의 안정성 및 rank 분석이 되어있나요?

### ISSUE THREAD

**Issue by JinraeKim** [fdcl-data-driven-control/data-driven-control#7]
[#16, DataDrivenControl.jl](https://github.com/fdcl-data-driven-control/DataDrivenControl.jl/issues/16) (이슈 위치를 여기에 파야했었는데 죄송... 옮길 수 있나?) 에서 policy iteration 기반의 linear-quadratic IRL 을 따라가고 있었는데요.

Kleinman 알고리즘은 기본적으로 offline 인데, online 으로 쓸 때의 안정성이 분석되었나요?
+) Least-square sense 로 업데이트 시, 얻어진 regressor matrix 가 full rank 가 될 조건이 제시되지 않아, 늘 update 가 잘 될지 의문스럽기도 하네요.

안 되어있다면, 해보는 것도 나쁘진 않을듯 합니다.
혹시 아시는 분?

**Comment by hnlee77** [comment]
제 기억에는 Jaeyoung Lee 가 이 쪽을 조금 살펴봤던 걸로 기억을 하는데 정확하진 않습니다. 이 분 논문을 좀 찾아보면서 분석해보면 괜찮을 것 같습니다.

**Comment by JinraeKim** [comment]
> 제 기억에는 Jaeyoung Lee 가 이 쪽을 조금 살펴봤던 걸로 기억을 하는데 정확하진 않습니다. 이 분 논문을 좀 찾아보면서 분석해보면 괜찮을 것 같습니다.

논문 링크 공유 가능할까요?

**Comment by hnlee77** [comment]
그 논문이 정확히 기억이 나질 않아서요 ㅠ 찾아보고 찾게되면 공유하도록 하겠습니다.
nonlinear system에 대한 논문은 [이것](https://ieeexplore.ieee.org/document/6882245)인 것 같습니다.

**Comment by hnlee77** [comment]
> Kleinman 알고리즘은 기본적으로 offline 인데, online 으로 쓸 때의 안정성이 분석되었나요? +) Least-square sense 로 업데이트 시, 얻어진 regressor matrix 가 full rank 가 될 조건이 제시되지 않아, 늘 update 가 잘 될지 의문스럽기도 하네요.
> 
> 안 되어있다면, 해보는 것도 나쁘진 않을듯 합니다. 혹시 아시는 분?

알고리즘의 업데이트 주기 T가 꼭 일정하지 않아도 된다는 것이 논문에 항상 명시되어 있었는데, 이것을 rank조건을 만족하도록 업데이트 하는 장치를 추가하는 건 어때요? (예를 들어 간단하게는 새로 쌓는 데이터 열의 독립조건을 확인하는 등)

**Comment by JinraeKim** [comment]
@hnlee77 불필요한 데이터를 넣지 않아도 되서 pseudo inverse 구할 때는 효과적일 것 같습니다.
그런데 예를 들어, 특정 iter 에서의 제어기로부터 나온 데이터가 만든 regressor 벡터가 늘 선형종속인 경우는 발생하지 않을까요?

그 여부 및 발생할 수 있는 예제가 있다면, 체계적인 방법으로 이를 방지할 수 있어도 좋을 것 같네요...!

**Comment by JinraeKim** [comment]
반례는 찾기 쉬운 것 같습니다.
LQ 문제에서 regressor의 각 원소의 차수가 모두 2차이므로, 
x_i_dot = u_i
인 시스템에서 u_i = -k x_i 와 같은 선형 제어기를 사용하면 궤적이 직선을 그리게 되고, 모든 regressor 벡터가 한 직선상에 존재하게 되네요.

**Comment by hnlee77** [comment]
> 반례는 찾기 쉬운 것 같습니다. LQ 문제에서 regressor의 각 원소의 차수가 모두 2차이므로, x_i_dot = u_i 인 시스템에서 u_i = -k x_i 와 같은 선형 제어기를 사용하면 궤적이 직선을 그리게 되고, 모든 regressor 벡터가 한 직선상에 존재하게 되네요.

오 그렇네요. 이런경우에는 exploration이 필수적으로 들어가야 겠네요. exploration을 체계적으로 하는 방법(?) 을 생각해 볼 수 있겠어요.

**Comment by JinraeKim** [comment]
> 오 그렇네요. 이런경우에는 exploration이 필수적으로 들어가야 겠네요. exploration을 체계적으로 하는 방법(?) 을 생각해 볼 수 있겠어요.

직관적으로는 확률적으로, 또는 주기적인 진동을 주는 식으로 하면 개선이 될 것 같은데요.
이걸 이론적으로도 잘 풀어낼 수 있으면 베스트일듯 (또는 이미 그런 논문이 있는지 찾아보거나).

하나의 직관은, 제어입력이 u + u_exploration 라면, u_exploration 의 크기는 exponentially decaying 해야 할 것 같네요 (그래야 infinite-horizon 에서 cost 가 발산하지 않을듯?).

**Comment by seong-hun** [comment]
아래 심형보 교수님의 설명글을 보면 도움이 될 것처럼 보이네요.

[2019 - 심형보 - 불확실한 선형 시스템에 대한 Data-Driven LQR.pdf](https://github.com/fdcl-data-driven-control/data-driven-control/files/7811107/2019.-.-.Data-Driven.LQR.pdf)

**Comment by JinraeKim** [comment]
> 아래 심형보 교수님의 설명글을 보면 도움이 될 것처럼 보이네요.
> 
> [2019 - 심형보 - 불확실한 선형 시스템에 대한 Data-Driven LQR.pdf](https://github.com/fdcl-data-driven-control/data-driven-control/files/7811107/2019.-.-.Data-Driven.LQR.pdf)

오... 좋은 참고자료네요.

읽어보니 수렴성/해의 존재성 등은 모두 "충분히 시스템을 잘 흔들었다" 는 PE 조건으로 설명하는군요.
결국 모든건 PE 를 완화하는 문제로 귀결되는건가... ㅋㅋㅋ

**Comment by seong-hun** [comment]
음.. 확실히 최적화 관점, 특히 이 이슈의 주제인 Rank 관점에선 그렇게 볼 수 있을 것 같습니다.

**Comment by seong-hun** [comment]
가치 함수를 과연 데이터 만으로 추정할 수 있을 것인가? -> ANN에서 다루는 주제

적당한 가치 함수의 iteration이 존재하여 최적 제어기를 얻을 수 있는가 -> 강화학습에서 다루는 주제 

이렇게 보면 적당하지 않을까요?

**Comment by JinraeKim** [comment]
> 오... 좋은 참고자료네요.
> 
> 읽어보니 수렴성/해의 존재성 등은 모두 "충분히 시스템을 잘 흔들었다" 는 PE 조건으로 설명하는군요. 결국 모든건 PE 를 완화하는 문제로 귀결되는건가... ㅋㅋㅋ

가정을 도입하긴 하나, 이를 분석하는 방법이 제시되어 이 이슈를 닫음
